ndeleche/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('skills/', views.skills, name='skills'),
    path('folio/', views.folio, name='folio'),
    path('contact/', views.contact, name='contact'),

]

portifolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ndeleche.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ndeleche/models.py
from django.db import models

# HOME SECTION.


class Home(models.Model):
    name = models.CharField(max_length=20)
    greetings_1 = models.CharField(max_length=20)
    greetings_2 = models.CharField(max_length=20)
    picture = models.ImageField(upload_to='picture/')

    # save time when modified
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


# ABOUT SECTION.

class About(models.Model):
    heading = models.CharField(max_length=50)
    career = models.CharField(max_length=20)
    description = models.TextField(blank=False)
    profile_img = models.ImageField(upload_to='profile/')
    resume = models.FileField(
        upload_to='resume/', default='NDELECHEHAMISNEW.pdf')

    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.career

# PROFILE SECTION.


class Profile(models.Model):
    about = models.ForeignKey(About, on_delete=models.CASCADE)
    social_name = models.CharField(max_length=10)
    link = models.URLField(max_length=200)

# SKILLS SECTION.


class Category(models.Model):
    name = models.CharField(max_length=20)

    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'skill'
        verbose_name_plural = 'skills'

    def __str__(self):
        return self.name


class Skills(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    skill_name = models.CharField(max_length=20)


# PORTIFOLIO SECTION

class Portifolio(models.Model):
    image = models.ImageField(upload_to='portifolio/')
    link = models.URLField(max_length=200)

    def __str__(self):
        return f'portifolio {self.id}'

#  FEEDBACK SECTION


class Feedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    feedback = models.TextField()

    def __str__(self):
        return self.name

ndeleche/views.py
from django.shortcuts import render
from .models import Home, About, Profile, Category, Skills, Portifolio, Feedback


# Index page.

def index(request):

    # home
    home = Home.objects.latest('updated')

    # portifolio
    portifolios = Portifolio.objects.all()

    context = {
        'home': home,
        'portifolios': portifolios

    }

    return render(request, 'index.html', context)


def about(request):

    # home
    home = Home.objects.latest('updated')

    # about
    about = About.objects.latest('updated')
    profiles = Profile.objects.filter(about=about)

    context = {
        'home': home,
        'profiles': profiles,
        'about': about,

    }

    return render(request, 'about.html', context)


def skills(request):

    # home
    home = Home.objects.latest('updated')

    # skills
    categories = Category.objects.all()

    context = {
        'home': home,
        'categories': categories,

    }
    return render(request, 'skills.html', context)


def folio(request):
    # home
    home = Home.objects.latest('updated')

    # portifolio
    portifolios = Portifolio.objects.all()

    context = {
        'home': home,
        'portifolios': portifolios

    }

    return render(request, 'folio.html', context)


def contact(request):

    context = {}  # Initialize the context dictionary

    if request.method == "POST":
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        feedback_text = request.POST.get('feedback', '')

        # Save the feedback
        obj = Feedback(name=name, email=email, feedback=feedback_text)
        obj.save()

        # Update the context to include feedback information
        context['feedback_submitted'] = True

    # Render the index page with the updated context
    return render(request, 'contact.html', context)

ndeleche/templates/about.html
{% extends 'main.html' %}

{% load static %}

{% block title %} {% endblock %}

{% block content %}
   
        <!--code here-->
        
<!--===== ABOUT =====-->
<section class="about section" id="about">
    <h2 class="section-title">About</h2>

    <div class="about__container bd-grid">
        <div class="about__img">
            <img src="{{about.profile_img.url}}" alt="">
        </div>

        <div>
            <h2 class="about__subtitle">{{ about.heading}}</h2>
            <span class="about__profession">{{ about.career}}</span>
            <p class="about__text">{{about.description}} </p>

            <div class="about__social">
                <a href="https://github.com/ndeleche" class="about__social-icon"><i class='bx bxl-github' ></i></a>
                <a href="https://www.linkedin.com/in/ndeleche-hamis-16b36b286/?originalSubdomain=tz" class="about__social-icon"><i class='bx bxl-linkedin' ></i></a>
                <a href="https://www.instagram.com/iamndeleche/?next=%2F" class="about__social-icon"><i class='bx bxl-instagram' ></i></a>
            </div>
        </div>
    </div>
    
<center>
    <div class="">
        <div class="row">
            <div id="button">
                <center>
                    <h2>Download CV</h2>
                    <p>Click the button below to download the CV in PDF format.</p>
                </center>
            </div>
            <div class="col-md-6">
                <!-- Add a download link for your PDF file -->
                <a href="{{about.resume.url}}" class="button">
                    <span style="vertical-align:middle">Download</span>
                </a>
            </div>
        </div>
    </div>
</center>

</section>



<br><br>

{% include 'footer.html' %}
        
    {% endblock %}

ndeleche/templates/contact.html
{% extends 'main.html' %}

{% load static %}

{% block title %} {% endblock %}

{% block content %}
   
        <!--code here-->
        
<!--===== CONTACT =====-->
<section class="contact section" id="contact">
    <h2 class="section-title">Contact</h2>
<center>
    {% if feedback_submitted %}

    <div id="feedback-message">
        <h3>Feedback has been submitted</h3>
    </div>

    <script>
        // Automatically hide the feedback message after 5 seconds
        setTimeout(function() {
            document.getElementById("feedback-message").style.display = "none";
        }, 5000);
        
        // Prevent scrolling to the top after form submission
        document.querySelector('.contact__form').addEventListener('submit', function(event) {
            event.preventDefault(); // Prevent the default form submission behavior

            // Your form submission logic here
            // ...

            // Display feedback message and set timeout to hide it
            document.getElementById("feedback-message").style.display = "block";
            setTimeout(function() {
                document.getElementById("feedback-message").style.display = "none";
            }, 5000);
        });
    </script>
    {% endif %}



    <div class="contact__container bd-grid">
        <div class="contact__info">
            <h3 class="contact__subtitle">EMAIL</h3>
            <span class="contact__text">ndelechehamis@gmail.com</span>

            <h3 class="contact__subtitle">PHONE</h3>
            <span class="contact__text">+(255) 686 009 681</span>

            <h3 class="contact__subtitle">ADDRESS</h3>
            <span class="contact__text">DAR ES SALAAM, TANZANAIA</span>
        </div>

        <form action="" class="contact__form" method="post">
        {% csrf_token %}
        <div class="contact__inputs">
            <input name="name"  type="text" placeholder="Name" class="contact__input" required>
            <input name="email" type="mail" placeholder="Email" class="contact__input" required>
        </div>

        <textarea name="feedback" id="" cols="0" rows="10" class="contact__input" value="your feedback.." required></textarea>

        <input type="submit" value="Submit" class="contact__button">

       

    </form>
    </div>
</section>



<br><br>

{% include 'footer.html' %} 


        
    {% endblock %}

ndeleche/templates/cv.html
{% load static %}

<center>
    <div class="">
        <div class="row">
            <div class="col-md-6">
                <center>
                    <h2>Download CV</h2>
                    <p>Click the button below to download the CV in PDF format.</p>
                </center>
            </div>
            <div class="col-md-6">
                <!-- Add a download link for your PDF file -->
                <a href="path/to/your-cv.pdf" class="button">
                    <span style="vertical-align:middle">Download</span>
                </a>
            </div>
        </div>
    </div>
</center>

ndeleche/templates/folio.html
{% extends 'main.html' %}

{% load static %}

{% block title %} {% endblock %}

{% block content %}
   
        <!--code here-->

        
<!--===== PORTFOLIO =====-->
<section class="portfolio section" id="portfolio">
    <h2 class="section-title">Portfolio</h2>

    <div class="portfolio__container bd-grid">

        {% for portifolio in portifolios %}

        <div class="portfolio__img">
           
            <img src="{{portifolio.image.url}}" alt="">

            <div class="portfolio__link">
                <a href="{{portifolio.link}}" class="portfolio__link-name">View details</a>
            </div>
        </div>
        {% endfor %}
        
    </div>
</section>

<br><br>

{% include 'footer.html' %}  


        
    {% endblock %}

ndeleche/templates/footer.html
{% load static %}

{% block title %} {% endblock %}

{% block content %}
   
        <!--code here-->

        
<!--===== FOOTER =====-->
<footer class="footer section">
    <div class="footer__container bd-grid">
        <div class="footer__data">
            <h2 class="footer__title">Ndeleche Hamis</h2>
            <p class="footer__text">I'm Software Developer</p>
        </div>

        <div class="footer__data">
            <h2 class="footer__title">EXPLORE</h2>
            <ul>
                <li><a href="{% url 'index'%}" class="footer__link">Home</a></li>
                <li><a href="{% url 'about'%}" class="footer__link">About</a></li>
                <li><a href="{% url 'skills'%}" class="footer__link">Skills</a></li>
                <li><a href="{% url 'folio'%}" class="footer__link">Portfolio</a></li>
                <li><a href="{% url 'contact'%}" class="footer__link">Contact</a></li>
            </ul>
        </div>
        
        <div class="footer__data">
            <h2 class="footer__title">FOLLOW</h2>
            <a href="https://www.linkedin.com/in/ndeleche-hamis-16b36b286/?originalSubdomain=tz" class="footer__social"><i class='bx bxl-linkedin' ></i></a>
            <a href="https://www.instagram.com/iamndeleche/?next=%2F" class="footer__social"><i class='bx bxl-instagram' ></i></a>
            <a href="https://github.com/ndeleche" class="footer__social"><i class='bx bxl-github' ></i></a>
        </div>


    </div>
</footer>




        


        
    {% endblock %}

ndeleche/templates/home.html
{% load static %}

<link rel="stylesheet" href="{% static 'assets/css/animate.css' %}">

 <!--===== HOME =====-->
<section class="home" id="home">
    <div class="home__container bd-grid">
        <h1 class="home__title"><span>{{ home.greetings_1 }}</span><br>{{ home.greetings_2 }}</h1>

        <div class="home__scroll">
            <a href="{% url 'about' %}" class="home__scroll-link"><i class='bx bx-left-arrow-alt'></i>About me</a>
        </div>

        <img src="{{ home.picture.url }}" alt="" class="home__img">
    </div>
</section>

ndeleche/templates/index.html
{% extends 'main.html' %}

{% load static %}

{% block title %} {% endblock %}

{% block content %}
   
        <!--code here-->



     {% include 'home.html' %}


        
    {% endblock %}

ndeleche/templates/main.html
{% load static %}
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- ===== CSS ===== -->
        <link rel="stylesheet" href="{% static 'assets/css/styles.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/cv.css' %}">

        <!-- ===== BOX ICONS ===== -->
        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>

        <title> Ndeleche's Portfolio</title>

    </head>
    <body>

        <!--===== HEADER =====-->
        <header class="l-header">
            <nav class="nav bd-grid">
                <div>
                    <a href="{% url 'index' %}" class="nav__logo">{{ home.name}}</a>
                </div>

                <div class="nav__menu" id="nav-menu">
                    <ul class="nav__list">
                        <li class="nav__item"><a href="{% url 'index' %}" class="nav__link active">Home</a></li>
                        <li class="nav__item"><a href=" {% url 'about' %}" class="nav__link">About</a></li>
                        <li class="nav__item"><a href=" {% url 'skills' %} "class="nav__link">Skills</a></li>
                        <li class="nav__item"><a href=" {% url 'folio' %}" class="nav__link">Portfolio</a></li>
                        <li class="nav__item"><a href="{% url 'contact' %}" class="nav__link">Contact</a></li>
                    </ul>
                </div>

                <div class="nav__toggle" id="nav-toggle">
                    <i class='bx bx-menu'></i>
                </div>
            </nav>
        </header>

        <main class="l-main">

        {% block content %}
   
            <!--code here-->
            
         


      
        {% endblock %}

           
         

        </main>
            

        

        <!--===== SCROLL REVEAL =====-->
        <script src="https://unpkg.com/scrollreveal"></script>

        <!--===== MAIN JS =====-->
        <script src="{% static 'assets/js/main.js' %}"></script>
    </body>
</html>

ndeleche/templates/skills.html
{% extends 'main.html' %}

{% load static %}

{% block title %} {% endblock %}

{% block content %}
   
        <!--code here-->

        
<!--===== SKILLS =====-->
<section class="skills section" id="skills">
    <h2 class="section-title">Skills & Technologies </h2>

    <div class="skills__container bd-grid">
        <div class="skills__box">
        
        {% for category in categories %}
            <h3 class="skills__subtitle">{{category.name}}</h3>

            {% for skills in category.skills_set.all %}
            <span class="skills__name">{{skills.skill_name}}</span>
            {% endfor %}

        {% endfor %}

        </div>

        <div class="skills__img">
            <img src="{% static 'assets/img/skill.png' %}" alt="">
        </div>
    </div>
</section>


<br><br>

{% include 'footer.html' %}
    {% endblock %}